### ISSUE TITLE
[Discussion] Filter that checks for numerical sequences?

### ISSUE THREAD

**Issue by XapaJIaMnu** [hplt-project/empty-train#69]
Do we want a filter that checks for the presence of numerical sequences on both sides?
Looking through CCAligned, there's some places where numbers are present on one side, but absent on another, which suggests that the two sentences are not parallel. There are cases where numbers would differ on both sides (Currency conversions/imperial-metric system shenanigans etc).

Do we have a rule for that somewhere in bicleaner? Has anyone experimented with that @jelmervdl @ZJaume ?

**Comment by ZJaume** [comment]
Bicleaner Hardrules [already has](https://github.com/bitextor/bicleaner-hardrules/blob/60afa6c192ef49465057aa06e24a1d6b7fa4ce2f/src/hardrules/hardrules.py#L367) that rule (disabled by default), we could use it.

**Comment by jelmervdl** [comment]
I also have a [stand-alone filter](https://github.com/hplt-project/empty-train/blob/main/filters/num_mismatch.py) that does the same thing with some wiggle room

**Comment by XapaJIaMnu** [comment]
Ok, so we already have it and I didn't find it, so i think we can close this.
